name: Build Go app and push to Azure

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.17

      - name: Build
        run: go build -o build/go-app -v

      - name: Deploy to Azure
        uses: Azure/webapps-deploy@v2
        with:
          # Name of the Azure Web App
          app-name: go-azure-appservice
          # Applies to Web App only: Path to package or folder. *.zip, *.war, *.jar or a folder to deploy
          package: build/
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
